databases:
  - name: factopro
    databaseName: factopro
    user: factopro

services:
  - type: web
    name: facto-pro
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn morosidad_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: factopro
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
